
###############################################################################
# backup
###############################################################################

# working directory to stage backups
backup_staging_dir: /var/tmp/backups

